### PR TITLE
Switch to fetch, move test secrets, improve test reliability

### LINKED ISSUE #11: "Socket hang up" in node 19+
I'm getting `Error: socket hang up` in node v19.0.0 when the queue is empty.
I was not getting that error in node v18.20.5.

I think the issue came from here:
https://github.com/nodejs/node/pull/43522

### PR DESCRIPTION
**Pull request by ArtskydJ**
Switching from httpie to fetch fixes #11.  It could probably be fixed by tweaking `keepAlive` settings, but we're wanting to move toward `fetch` and away from `httpie` anyway.

### CODE REVIEW

**Comment by njbotkin** [comment]
Did you forget to commit a file?  I don't see the actual change to use fetch...

**Comment by ArtskydJ** [comment]
Yep.  I amended the commit to include it.

**Review by njbotkin — COMMENTED** [review]
looks equivalent to me, but you might want to dig into this:

[MDN fetch docs](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch):

> The [Response.status](https://developer.mozilla.org/en-US/docs/Web/API/Response/status) property tells us the numerical status code, and the [Response.ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) property returns true if the status is in the [200 range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#successful_responses).

[HTTPie docs](https://www.npmjs.com/package/httpie):

> If the response's statusCode is 400 or above, this Promise will reject with a formatted error – see [Error Handling](https://www.npmjs.com/package/httpie#error-handling). Otherwise, the Promise will resolve with the full [ClientRequest](https://nodejs.org/api/http.html#http_class_http_clientrequest) stream.

So, in theory, if the SQS API returns a 3xx code, the module will throw.  Previously it would not have.

**Comment by ArtskydJ** [comment]
Yeah, that's true.

But I can't find anywhere in the [SQS docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/Welcome.html) where it could return 3xx.

Regardless, I'm thinking this will be a breaking change.

**Comment by ArtskydJ** [comment]
Published in 2.0.0

**Pull request merged**
